---
title: "Data Science as a Field Project"
author: "Kate Borden, Evan McCormick, Paige Phillips"
date: "12/08/2022"
format: html
toc: true
editor: visual
page-layout: full
---

{r Import Packages, include=FALSE, echo = FALSE}
library(tidyverse)
library(dplyr)
library(stringr)
library(arules)
library(arulesViz)
library(ggplot2)


Statement of question and interest

Question: *What factors in personality and prior drug use are predominantly associated with the use of specific drugs – especially hard drugs?*

For our project we are interested in drug consumption and the association to personality and behavior. For instance, we want to further evaluate the different types of risk to be for each drug. We can split up the drugs based on how they are scheduled or classified as controlled substances. We are primarily interested in distinguishing which factors in personality and prior drug use are predominantly associated with the use of specific drugs. Secondly, we want to assess which factors are predominantly associated with hard drugs.

Source & Dataset Description

We got our database from here, see Drug Consumptions (UCI)

You can access our data here, see GitHub

Dataset Contents:

There are 12 attributes that are categorized based on their background demographic and personality measurements. These attributes are assessed across 18 central nervous system (CNS) psychoactive drugs. The drugs selected includes both illicit and licit.

Featured Attributes for Quantified Data

ID: total number of 1885 records in this database

Age: participant's age

Gender: binary of only fale or female

Education: participant's level of education

Country: participant's country of origin

Ethnicity: participant's ethnicity

Featured Attributes for Personality measurements (NEO-FFI-R)

Nscore: neuroticism

Escore: extraversion

Oscore: openness to experience.

Ascore: agreeableness.

Cscore: conscientiousness.

Impulsive: impulsiveness (measured by BIS-11)

SS: sensation seeing (measured by ImpSS)

Consumption usage of 18 legal and illegal drugs

Alcohol: alcohol consumption

Amphet: amphetamines consumption

Amyl: nitrite consumption

Benzos: benzodiazepine consumption

Caff: caffeine consumption

Cannabis: marijuana consumption

Choc: chocolate consumption

Coke: cocaine consumption

Crack: crack cocaine consumption

Ecstasy: ecstasy consumption

Heroin: heroin consumption

Ketamine: ketamine consumption

Legalh: legal highs consumption

LSD: LSD consumption

Meth: methadone consumption

Mushroom: magic mushroom consumption

Nicotine: nicotine consumption

Semer: class of fictitious drug Semeron consumption (i.e. control)

VSA: class of volatile substance abuse consumption

Rating's for Drug Use

CL0: Never Used

CL1: Used over a Decade Ago

CL2: Used in Last Decade

CL3: Used in Last Year 59

CL4: Used in Last Month

CL5: Used in Last Week

CL6: Used in Last Day

Examining the Data

{r read in data, echo = FALSE }
# read in file directly from kaggle

df <- read.csv(url("https://raw.githubusercontent.com/paph3285/Drug_Consumption/main/Drug_Consumption.csv"))


Subset dataframe

{r Subset Dataframe, echo = FALSE}

Subset_Drugs <- df %>% select(-c("ID", "Ethnicity", "Country", "Education", "Age", "Gender", "Caff", "Choc", "Semer","Nscore","Escore","Oscore","AScore","Cscore","Impulsive","SS"))

knitr::kable(
  head(Subset_Drugs)
  )

Cleaning the data

{r Clean Data, echo=FALSE}

categorical_columns = c('Alcohol', 'Amphet', 'Amyl', 'Benzos', 'Cannabis', 'Coke', 'Crack', 'Ecstasy', 'Heroin', 'Ketamine', 'Legalh', 'LSD', 'Meth', 'Mushrooms', 'Nicotine', 'VSA')

# We will drop overclaimers since, there answers might not truly be accurate

# We will also drop unnecesary columns

# convert drug columns to numericaL
for (col in categorical_columns) {
  Subset_Drugs[col] = as.numeric(gsub("CL", "", Subset_Drugs[, col]))
  
  # categorize drug column as either 'used' (1) or 'never used' (0)
  # if Drugs[col] == 0 (never used) or Drugs[col] == 1 (used over a decade ago), cateogorize them as a non-user
  Subset_Drugs[,col]=ifelse((Subset_Drugs[,col] == 0 | Subset_Drugs[,col] == 1), 0, 1)
}


{r Combining Columns, echo = FALSE}
# combine columns of similar drugs

Subset_Drugs <- Subset_Drugs %>%
  mutate(Psychedelics = pmax(LSD, Mushrooms), Sedatives = pmax(Alcohol, Benzos, Ketamine), Stimulants = pmax(Amphet,Coke,Crack,Ecstasy,Meth))

knitr::kable(
  head(Subset_Drugs)
  )
# Cannabis shouldn't be OTC, this survey was predominantly done in the UK, in which Marijuana remains a controlled substance. Illegal columns doesn't make any sense as most of these drugs are illegal to use recreational. We should use the inverse of "OTC" instead.

Analysis

Using Frequency Pattern Analysis to find common patterns in drug use.

{r Creating a Dataframe for FP, echo = FALSE}

All_Trans <- ( Subset_Drugs > 0 )
All_Trans <- as.data.frame( Subset_Drugs > 0)
Drug_Trans <- All_Trans %>% select(`Alcohol`:`VSA`)
No_OTC <- All_Trans %>% select(-c(`Alcohol`,`Nicotine`,`Cannabis`,`Psychedelics`,`Stimulants`,`Sedatives`))
Hard_Trans <- No_OTC %>% select(-c(`Ecstasy`,`Mushrooms`))
Class_Trans <- All_Trans %>% select(`Psychedelics`:`Stimulants`)

drug_rules <- apriori(Drug_Trans,list(
  support = 0.4,
  confidence = 0.9,
  minlen = 2
))

inspect(drug_rules)



{r FP rules for hard drugs (no alcohol, tobacco, weed, or general groupings), echo = FALSE}
hard_drug_rules <- apriori(No_OTC,list(
 support = 0.18,
 confidence = 0.9,
 minlen = 2
))

inspect(hard_drug_rules)


{r echo = FALSE}

hard_rules <- apriori(Hard_Trans,list(
 support = 0.11,
 confidence = 0.9,
 minlen = 2
))

inspect(hard_rules)


{r drug class Rules, echo = FALSE}
class_rules <- apriori(Class_Trans,list(
 support = 0.4,
 confidence = 0.9,
 minlen = 2
))

inspect(class_rules)


Conclusion

One pattern found in the data is that people's drug use tends to cluster around specific groups of drugs. Using Frequency Pattern (FP) analysis, popular drug groupings are found at various levels of popularity.

{r echo = FALSE}

plot(class_rules, method = "graph", measure = "support", shading = "support") + scale_color_gradient()


{r echo = FALSE}
plot(drug_rules, method = "graph", measure = "support", shading = "support") + scale_color_gradient()


When looking at all drug relations, the most common 'basket' of drugs used in combination is the three most common drugs used: Alcohol, Cannabis, and Nicotine. While these three are often used together, they are also found to be the main drug used in combination with other, less common drugs. This shows their status as "gateway" drugs. Nearly everyone who uses some of the harder, less common drugs also uses one of these three.

{r echo = FALSE}

plot(hard_rules, method = "graph", measure = "support", shading = "support") + scale_color_gradient()


When removing the three 'gateway' drugs from the market baskets, a new pattern emerges. Around 20% of drug users use a combination of drugs including Cocaine, Amphetamine, LSD, Mushrooms, Benzos and Ecstasy (MDMA). These drugs are a varied group, and could be considered "medium" drugs, although some of them, such as Amphetamines and Benzodiazapines, are as volatile as the 'harder' drugs included in this data table. Within this group of drugs, Psilocybin and Ecstasy appear to act as the "gateway".

{r echo = FALSE}
plot(hard_drug_rules, method = "graph", measure = "support", shading = "support") + scale_color_gradient()

Group Biases -

Some personal biases that we can acknowledge from this project and dataset are the "Drugs" listed. We would have refrained from classifying a handful of the drugs presented and would not have included them in the original dataset. Precisely alcohol, caffeine, chocolate, and possibly legal highs.

A possible explanation to our bias, is due to how prevalent or not these specifics drugs are in our world. Alcohol, caffeine, chocolate, and let's say marijuana may be more accessibly available, depending on where you live, than let's say meth, heroin, or benzos, and so forth.

Another example of bias is social pressure and cultural differences. How that may influence our unconscious biases of different drugs. For example marijuana and psilocybin are becoming popular alternative drugs to use for medical and recreational purposes in the U.S., but that may not reflect the same for in the U.K. or Australia per say. How we perceive the classification and use of these drugs holds lots of bias.

Lastly, the word "drug(s)" carries a negative connotation behind it. More often than not one mind jumps to 1) illegal, 2) substance use disorder (SUD), 3) problematic. Again, a lot of these are associated with more illicit drugs like cocaine, meth, heroin, etc., not so much with alcohol, chocolate, caffeine, and marijuana. How we perceive these drugs is a bias of itself. If we were to not include some of these drugs in the dataset, that would be unethical of us as a data scientist.

SessionInfo

{r ,echo = FALSE}

sessionInfo()

